server:
  port: 8081
  servlet:
    context-path: /service1
spring:
  application:
    name: service1-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:4000/eureka
